package me.taste2plate.app.customer.presentation.navigation

class Routes{
    companion object {
        const val splashRoute: String = "splash"
        const val onBoardingRoute: String = "onboarding"
        const val signInRoute: String = "signIn"
        const val signUpRoute: String = "signUp"
        const val homeRoute: String = "home"
        const val otpRoute: String = "otp"
        const val locationRoute: String = "location"
        const val orderListRoute: String = "orderlist"
        const val profileRoute: String = "profile"
        const val cityBrandRoute: String = "cityBrand"
        const val productListRoute: String = "productList"
        const val detailsRoute: String = "detailsRoute"
        const val bulkOrderRoute: String = "bulkOrderRoute"
        const val membershipRoute: String = "membershipRoute"
        const val myPlanRoute: String = "myPlanRoute"
        const val productDetailsRoute: String = "productDetails"
        const val walletRoute: String = "walletRoute"
        const val contactUsRoute: String = "contactUsRoute"
        const val wishlistRoute: String = "wishlistRoute"
        const val cartRoute: String = "cartRoute"
        const val editProfileRoute: String = "editprofile"
        const val addressListRoute: String = "addressList"
        const val addEditAddressRoute: String = "addeditaddress"
        const val notificationRoute: String = "notificationRoute"
        const val locationPermissionRoute: String = "locationPermissionRoute"
        const val orderDetailsRoute: String = "orderdetails"
        const val checkoutRoute: String = "checkoutRoute"
        const val OrderConfirmRoute: String = "OrderConfirmRoute"
        const val requestPermissionRoute: String = "requestpermission"
    }
}
